#!/bin/bash

echo "==============================================="
echo "🏦 BANKING API - STATUS & DEMO"
echo "==============================================="
echo ""
echo "🚀 Application Status:"
echo "   ✅ Server Running: http://localhost:3000"
echo "   ✅ API Base URL: http://localhost:3000/api/v1"
echo "   ✅ Database: MySQL (banking_api) CONNECTED"
echo "   ✅ Prisma Client: Generated & Ready"
echo "   ✅ All modules loaded successfully"
echo ""
echo "📦 Modules Loaded:"
echo "   ✅ AuthModule - JWT Authentication"
echo "   ✅ AccountsModule - Bank Accounts"
echo "   ✅ TransactionsModule - Deposits, Withdrawals, Transfers"
echo "   ✅ CardsModule - Debit/Credit Cards"
echo "   ✅ BeneficiariesModule - Saved Recipients"
echo "   ✅ LoansModule - Loan Applications"
echo "   ✅ NotificationsModule - User Notifications"
echo "   ✅ AdminModule - Admin Panel"
echo "   ✅ ThrottlerModule - Rate Limiting"
echo ""
echo "📡 Available API Endpoints:"
echo ""
echo "   🔐 Authentication (/api/v1/auth):"
echo "   - POST   /register"
echo "   - POST   /login"
echo "   - POST   /refresh"
echo "   - POST   /logout"
echo "   - GET    /profile"
echo ""
echo "   💰 Accounts (/api/v1/accounts):"
echo "   - POST   / (Create account)"
echo "   - GET    / (Get all accounts)"
echo "   - GET    /balance/:accountNumber"
echo "   - GET    /:id"
echo "   - PATCH  /:id"
echo "   - DELETE /:id"
echo ""
echo "   💸 Transactions (/api/v1/transactions):"
echo "   - POST   /deposit"
echo "   - POST   /withdraw"
echo "   - POST   /transfer"
echo "   - POST   /payment"
echo "   - GET    / (Transaction history)"
echo "   - GET    /:id"
echo ""
echo "   💳 Cards (/api/v1/cards):"
echo "   - POST   / (Request card)"
echo "   - GET    / (Get all cards)"
echo "   - GET    /:id"
echo "   - PATCH  /:id/activate"
echo "   - PATCH  /:id/block"
echo "   - PATCH  /:id/pin"
echo "   - DELETE /:id"
echo ""
echo "   👥 Beneficiaries (/api/v1/beneficiaries):"
echo "   - POST   / (Add beneficiary)"
echo "   - GET    / (Get all)"
echo "   - GET    /:id"
echo "   - DELETE /:id"
echo ""
echo "   🏦 Loans (/api/v1/loans):"
echo "   - POST   /apply (Apply for loan)"
echo "   - GET    / (Get all loans)"
echo "   - GET    /:id"
echo "   - PATCH  /:id/approve (Admin)"
echo "   - POST   /:id/payment (Make payment)"
echo "   - GET    /:id/schedule (Payment schedule)"
echo ""
echo "   🔔 Notifications (/api/v1/notifications):"
echo "   - GET    / (Get notifications)"
echo "   - GET    /unread-count"
echo "   - PATCH  /:id/read"
echo "   - PATCH  /read-all"
echo "   - DELETE /:id"
echo ""
echo "   🛡️  Admin (/api/v1/admin) [ADMIN ONLY]:"
echo "   - GET    /users"
echo "   - GET    /transactions"
echo "   - GET    /audit-logs"
echo "   - GET    /statistics"
echo "   - PATCH  /users/:id/status"
echo "   - PATCH  /users/:id/role"
echo ""
echo "==============================================="
echo "✅ PROJECT STATUS: RUNNING & READY"
echo "==============================================="
echo ""
echo "📝 Quick Test Examples:"
echo ""
echo "1. Register User:"
echo '   curl -X POST http://localhost:3000/api/v1/auth/register \'
echo '     -H "Content-Type: application/json" \'
echo '     -d '"'"'{
       "email":"user@bank.com",
       "password":"Pass123!",
       "fullName":"John Doe",
       "phoneNumber":"+628123456789"
     }'"'"
echo ""
echo "2. Login:"
echo '   curl -X POST http://localhost:3000/api/v1/auth/login \'
echo '     -H "Content-Type: application/json" \'
echo '     -d '"'"'{"email":"user@bank.com","password":"Pass123!"}'"'"
echo ""
echo "3. Create Account (with JWT token):"
echo '   curl -X POST http://localhost:3000/api/v1/accounts \'
echo '     -H "Content-Type: application/json" \'
echo '     -H "Authorization: Bearer YOUR_TOKEN" \'
echo '     -d '"'"'{"accountType":"SAVINGS","currency":"IDR"}'"'"
echo ""
echo "4. Deposit Money:"
echo '   curl -X POST http://localhost:3000/api/v1/transactions/deposit \'
echo '     -H "Content-Type: application/json" \'
echo '     -H "Authorization: Bearer YOUR_TOKEN" \'
echo '     -d '"'"'{"accountNumber":"ACC123456","amount":1000000}'"'"
echo ""
echo "==============================================="
echo "🎓 Week 24 - Banking API with NestJS"
echo "==============================================="
